language: android

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8
    - ANDROID_TARGET=android-26
    - ANDROID_ABI=armeabi-v7a

before_script:
  # Emulator Management: Create, Start and Wait
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

before_install:
- chmod +x gradlew

android:
  components:
    - build-tools-28.0.3
    - $ANDROID_TARGET
    # Run emulator
    - sys-img-armeabi-v7a-$ANDROID_TARGET
